### ISSUE TITLE
Exemplar list for exemplar-based methods

### ISSUE THREAD

**Issue by gsustar** [ActiveVisionLab/ABC123#3]
Hi @mahobley ,

Thank you for your excellent work!

In the paper I see that you evaluated multiple 3-shot methods on the MCAC dataset, that require 3 exemplars as input in order to count the objects on the image. I would kindly request if you could share the evaluation protocol for these methods. More specificaly if you could share the list of bounding boxes that you used as examplars for these methods. This would allow future exemplar-based methods to compare their results with the ones you obtained.

Thanks again!

**Comment by mahobley** [comment]
The evaluation protocol is to use the three least occluded bounding boxes (lowest index to break ties), this gives exemplar methods the best chance at success.
We have added json files with the index of these bounding boxes for ease of use
[https://github.com/ActiveVisionLab/MCAC/tree/main/eval_bboxes](https://github.com/ActiveVisionLab/MCAC/tree/main/eval_bboxes)

**Comment by gsustar** [comment]
Hi,

When checking the total numbe of `obj_id`'s in the provided json files for the test and eval split I noticed that their lenghts were 3641 and 4287 respectively. This corresponds to the lengths of the dataset if you set the occlusion limit to 100% (so the entire dataset). However In the `configs/ABC123test.yml` file the occlusion limit is set to 70%. So I would assume that during evaluation you keep the occlusion limit to 70%. However, as far as I know this limit removes certain classes/`obj_id`'s from the evaluation datasets. In my implementation, with the occlusion limit set to 70% I get, 3630 classes for the test set and 4274 classes for the validation set.

Can you confirm that this is the correct approach and that these are the correct lenghts of the dataset for exemplar based methods?

Thanks.

**Comment by mahobley** [comment]
You are correct that the same 70% occlusion limit is used during testing.
The occlusion is for not counting specific objects within an image rather than not looking at specific images or classes.
I don't have a way of checking it right now and I didnt generate this number explicitly at any point, but I could easily believe that there are around ~15 images in a split where all instances of a class are occluded >70% which would lead to the numbers you have found.
